# Generated by Django 2.2.4 on 2019-08-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roaster',
            name='isDisplayed',
            field=models.BooleanField(default=False),
        ),
    ]
