# Generated by Django 3.0.7 on 2020-07-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationApp', '0002_beverage_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactInfo', models.CharField(max_length=50)),
                ('contactType', models.CharField(max_length=50)),
                ('isDisplayed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(max_length=50)),
                ('daysOfTheWeek', models.CharField(max_length=2)),
                ('isDisplayed', models.BooleanField(default=True)),
            ],
        ),
    ]
