# Generated by Django 2.2.4 on 2019-08-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigurationApp', '0002_roaster_isdisplayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='isDisplayed',
            field=models.BooleanField(default=True),
        ),
    ]
